/**
 * Grounding guard for Granite answers.
 *
 * Checks whether a model answer contains numerical, object-name, or directional
 * claims that the sky context does not support. A claim that cannot be verified
 * is reported in the returned list; the caller decides what to do with it.
 *
 * The guard is deliberately conservative in BOTH directions. A false positive
 * (blocking a correct answer) is as damaging as a false negative (letting a
 * hallucination through), because every rejection drops the user to the plainer
 * local narrator. When in doubt, the check passes.
 *
 * This module imports nothing from src/ and nothing from node_modules.
 */

import { STAR_NAMES as STAR_NAMES_ARRAY } from './star-names.js';

// ---------------------------------------------------------------------------
// Public interface
// ---------------------------------------------------------------------------

export interface GroundingReport {
  /** False when the answer makes at least one claim the context does not support. */
  ok: boolean;
  /** Human-readable list of the unsupported claims, for the retry prompt and logs. */
  unsupported: string[];
}

export function checkGrounding(answer: string, context: unknown): GroundingReport {
  const unsupported: string[] = [
    ...checkMeasurements(answer, context),
    ...checkNamedObjects(answer, context),
    ...checkDirections(answer, context),
  ];
  return { ok: unsupported.length === 0, unsupported };
}

// ---------------------------------------------------------------------------
// Compass vocabulary
//
// These are the exact strings that compassPoint() in src/lib/astro/satellites.ts
// produces. They are copied here rather than imported so that this module stays
// dependency-free. If compassPoint() is ever extended, update this list too.
// ---------------------------------------------------------------------------

const COMPASS_POINTS = [
  'north',
  'north-north-east',
  'north-east',
  'east-north-east',
  'east',
  'east-south-east',
  'south-east',
  'south-south-east',
  'south',
  'south-south-west',
  'south-west',
  'west-south-west',
  'west',
  'west-north-west',
  'north-west',
  'north-north-west',
];

// ---------------------------------------------------------------------------
// Known astronomical body names
//
// These are the names worth checking. buildSkyContext only ever receives the
// Sun, Moon, eight planets, and satellites -- never stars. A star name in the
// answer therefore cannot be supported by anything in the context, which is
// exactly the hallucination this list exists to catch.
//
// Solar-system bodies (Sun, Moon, planets) appear in the context by name, so
// they self-verify through the number check when they come with a measurement,
// and through this list when the name appears alone.
//
// Star names are generated at module initialisation from the real HYG catalogue
// embedded in the app's public/ directory. Typing them by hand would be both
// error-prone and a maintenance burden as the catalogue evolves.
// ---------------------------------------------------------------------------

const SOLAR_SYSTEM_NAMES = [
  'Sun', 'Moon',
  'Mercury', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune',
  'Pluto',
  'ISS', 'Tiangong',
];

/**
 * Names that are always allowed regardless of context content.
 * Earth is never in the context (we are standing on it), Milky Way and
 * Borrowed Sky are background prose, and compass names are handled separately.
 */
const ALWAYS_PERMITTED = new Set<string>([
  'Earth', 'Milky Way', 'Borrowed Sky',
  ...COMPASS_POINTS.map((p) => p.split('-').map(capitalise).join('-')),
  ...COMPASS_POINTS.map((p) => p.split('-').map(capitalise).join(' ')),
  'N', 'NE', 'E', 'SE', 'S', 'SW', 'W', 'NW',
  'NNE', 'ENE', 'ESE', 'SSE', 'SSW', 'WSW', 'WNW', 'NNW',
]);

function capitalise(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

/**
 * Star names from the HYG catalogue, generated by scripts/build-catalog.mjs
 * and committed as api/_lib/star-names.ts. A static import works in any
 * deployment environment, including Vercel serverless functions where public/
 * is served as CDN assets and is not present on the filesystem.
 */
const STAR_NAMES: Set<string> = new Set(STAR_NAMES_ARRAY);

// All body names to check, combining solar-system and catalogue stars.
function knownBodyNames(): string[] {
  return [...SOLAR_SYSTEM_NAMES, ...STAR_NAMES];
}

// ---------------------------------------------------------------------------
// Context utilities
// ---------------------------------------------------------------------------

/**
 * Recursively walks an arbitrary JSON value and returns every number found,
 * plus every number embedded in a string value (thousands separators stripped).
 *
 * The pool deliberately mixes all numbers regardless of what they measure.
 * That means "magnitude 47" would pass if some object happened to sit at
 * altitude 47. The alternative -- tracking which number came from which field
 * -- would require this module to know the SkyContext schema, which it must
 * not. For now, pooling is accepted as a known limitation and the comment
 * below records it rather than hiding it.
 *
 * context.observedAt is excluded. It is an ISO timestamp string, so pulling
 * digits out of it injects numbers like 2026, 08, 18, 13, 04 that are
 * meaningless as astronomical measurements and give false claims accidental cover.
 */
function collectNumbers(value: unknown, key?: string): number[] {
  if (key === 'observedAt') return [];

  if (typeof value === 'number' && isFinite(value)) return [value];

  if (typeof value === 'string') {
    // Strip thousands separators before scanning, because the context contains
    // strings like "384,400 km away".
    const cleaned = value.replace(/,(?=\d{3})/g, '');
    const found: number[] = [];
    for (const m of cleaned.matchAll(/-?\d+(?:\.\d+)?/g)) {
      const n = parseFloat(m[0]);
      if (isFinite(n)) found.push(n);
    }
    return found;
  }

  if (Array.isArray(value)) {
    return value.flatMap((item) => collectNumbers(item));
  }

  if (value !== null && typeof value === 'object') {
    return Object.entries(value as Record<string, unknown>).flatMap(([k, v]) =>
      collectNumbers(v, k),
    );
  }

  return [];
}

/** Collects every string that appears anywhere in the context, flattened. */
function collectStrings(value: unknown): string[] {
  if (typeof value === 'string') return [value];
  if (Array.isArray(value)) return value.flatMap(collectStrings);
  if (value !== null && typeof value === 'object') {
    return Object.values(value as Record<string, unknown>).flatMap(collectStrings);
  }
  return [];
}

// ---------------------------------------------------------------------------
// Tolerance check
//
// Granite is explicitly told in the system prompt to round and approximate
// ("about a third of the way up in the south-east"), so exact matching would
// reject correct answers. The tolerance is 0.5 absolute or 5% relative,
// whichever is larger.
// ---------------------------------------------------------------------------

function withinTolerance(answer: number, context: number): boolean {
  return Math.abs(answer - context) <= Math.max(0.5, 0.05 * Math.abs(context));
}

function isSupportedByContext(value: number, contextNumbers: number[]): boolean {
  return contextNumbers.some((c) => withinTolerance(value, c));
}

// ---------------------------------------------------------------------------
// Check a: measurements
// ---------------------------------------------------------------------------

interface Measurement {
  raw: string;
  value: number;
}

/**
 * Extracts numbers that carry an astronomical unit or role next to them.
 * Bare numbers in prose ("two planets are up") are ignored.
 */
function extractMeasurements(answer: string): Measurement[] {
  const results: Measurement[] = [];

  // Patterns, each as [regex, capture-group-index-for-the-number].
  // The number group is always named `n` for clarity.
  const patterns: RegExp[] = [
    // degrees: "30 degrees", "30°", "30-degree"
    /(?<n>-?\d+(?:\.\d+)?)\s*(?:degrees?|°)/gi,
    // magnitude: "magnitude 1.4", "mag 3", "apparent magnitude of -1.4"
    // The optional "of" covers "apparent magnitude of X" which Granite sometimes produces.
    /\bmag(?:nitude)?\s+(?:of\s+)?(?<n>-?\d+(?:\.\d+)?)/gi,
    // distance: "384,400 km", "1.5 million km", "8 light years", "4.2 light-years"
    /(?<n>-?\d+(?:[.,]\d+)?)\s*(?:million\s+)?km\b/gi,
    /(?<n>-?\d+(?:\.\d+)?)\s*(?:million\s+)?(?:light.?years?|ly)\b/gi,
    // kilometres spelled out
    /(?<n>-?\d+(?:[.,]\d+)?)\s*kilometres?\b/gi,
    // percentage: "60% lit", "60 percent"
    /(?<n>-?\d+(?:\.\d+)?)\s*(?:%|percent(?:age)?)\b/gi,
    // duration: "in 12 minutes", "2 hours"
    /\bin\s+(?<n>\d+(?:\.\d+)?)\s*minutes?\b/gi,
    /\b(?<n>\d+(?:\.\d+)?)\s*hours?\b/gi,
    // clock time: "20:20", "8:42 pm"
    /\b(?<n>\d{1,2}):\d{2}(?:\s*[ap]m)?\b/gi,
  ];

  for (const pattern of patterns) {
    for (const match of answer.matchAll(pattern)) {
      const raw = match[0];
      const numStr = (match.groups?.n ?? '').replace(/,/g, '');
      const value = parseFloat(numStr);
      if (isFinite(value)) results.push({ raw, value });
    }
  }

  return results;
}

function checkMeasurements(answer: string, context: unknown): string[] {
  const measurements = extractMeasurements(answer);
  if (measurements.length === 0) return [];

  const contextNumbers = collectNumbers(context);
  const failures: string[] = [];

  for (const { raw, value } of measurements) {
    if (!isSupportedByContext(value, contextNumbers)) {
      failures.push(`"${raw}" (${value} -- nothing in tonight's data is within tolerance of it)`);
    }
  }

  return failures;
}

// ---------------------------------------------------------------------------
// Check b: named objects
// ---------------------------------------------------------------------------

function checkNamedObjects(answer: string, context: unknown): string[] {
  const contextText = collectStrings(context).join(' ').toLowerCase();
  const failures: string[] = [];

  for (const name of knownBodyNames()) {
    if (ALWAYS_PERMITTED.has(name)) continue;

    // Match the name as a whole word, case-insensitively.
    const pattern = new RegExp(`\\b${escapeRegex(name)}\\b`, 'i');
    if (!pattern.test(answer)) continue;

    // The name is in the answer -- check it appears somewhere in the context.
    if (!contextText.includes(name.toLowerCase())) {
      failures.push(`"${name}" (not in tonight's sky data)`);
    }
  }

  return failures;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// ---------------------------------------------------------------------------
// Check c: directions
// ---------------------------------------------------------------------------

/**
 * Returns the set of compass points that appear anywhere in the context,
 * normalised to canonical form.
 */
function directionsInContext(context: unknown): Set<string> {
  const text = collectStrings(context).join(' ').toLowerCase();
  const present = new Set<string>();
  for (const point of COMPASS_POINTS) {
    // Check both hyphenated and un-hyphenated forms.
    const unhyphenated = point.replace(/-/g, '');
    if (text.includes(point) || text.includes(unhyphenated)) {
      present.add(point);
    }
  }
  return present;
}

/**
 * Returns compass-vocabulary words that appear in the answer text, normalised.
 */
function directionsInAnswer(answer: string): string[] {
  const lower = answer.toLowerCase();
  const found: string[] = [];

  // Build a pattern that matches any variant of any compass point.
  for (const point of COMPASS_POINTS) {
    const unhyphenated = point.replace(/-/g, '');
    const spaceSeparated = point.replace(/-/g, ' ');
    const variants = [point, unhyphenated, spaceSeparated].map(escapeRegex);
    const pattern = new RegExp(`\\b(?:${variants.join('|')})\\b`, 'i');
    if (pattern.test(lower)) {
      found.push(point);
    }
  }

  return found;
}

function checkDirections(answer: string, context: unknown): string[] {
  const mentioned = directionsInAnswer(answer);
  if (mentioned.length === 0) return [];

  const inContext = directionsInContext(context);
  const failures: string[] = [];

  for (const point of mentioned) {
    if (!inContext.has(point)) {
      failures.push(`direction "${point}" (not used for any object in tonight's data)`);
    }
  }

  return failures;
}
